Repository FindTown/FindTown-iOS, pull requests merged in 2023-06, with the labels that each got.

#101 2차 오픈 전 수정 및 개선
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/FavoriteListResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TownFilterResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TownIntroduceResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TownSearchResponseDTO.swift
  FindTown/FindTown/Domain/Entities/TownTableModel.swift
  FindTown/FindTown/Domain/Enumerations/TownRank.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/FavoriteTableView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewController.swift
Labels: ✨ 기능, 💄 UI

#102 가입단계 분위기 태그 선택 기능 추가
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindTown/FindTown/Data/DataMapping/Reponse/MapThemaStoreResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Request/MemberSignupDTO.swift
  FindTown/FindTown/Domain/Entities/SingupUserModel.swift
  FindTown/FindTown/Domain/Entities/ThemaStore.swift
  FindTown/FindTown/Domain/Enumerations/InfraSubCategory.swift
  FindTown/FindTown/Domain/Enumerations/TownMood.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupViewModelDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMoodSelect/TownMoodSelectCollectionViewCell.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMoodSelect/TownMoodSelectHeaderView.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMoodSelect/TownMoodSelectViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMoodSelect/TownMoodSelectViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapInfraIconView.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapThemaIconView.swift
Labels: ✨ 기능

#104 2차 오픈 후 수정사항 반영
  FindTown/FindTown/Data/DataMapping/Reponse/FavoriteListResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TownFilterResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TownSearchResponseDTO.swift
  FindTown/FindTown/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  FindTown/FindTown/Domain/Entities/City.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/SearchScene/Search/SearchViewController.swift
  FindTown/FindTown/Presentation/SearchScene/Search/SubViews/ServiceMapPopUpViewController.swift
Labels: ♻️ 리팩토링

#105 키보드 로직 수정
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewController.swift
Labels: 🐞 버그
