Repository FindTown/FindTown-iOS, pull requests merged in 2023-02, with the labels that each got.

#63 동네지도 UI 개선
  FindTown/FindTown/Domain/Enumerations/StoreDetailType.swift
  FindTown/FindTown/Presentation/MapScene/AddressSheet/AddressSheetViewModel.swift
  FindTown/FindTown/Presentation/MapScene/AddressSheet/SubViews/CityCollectionViewFlowLayout.swift
  FindTown/FindTown/Presentation/MapScene/Flows/AddressSheetCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapCategoryCollectionViewCell.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapStoreCollectionViewCell.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/StoreCollectionViewFlowLayout.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/cafeIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/cafeIcon.imageset/cafeIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/chineseFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/chineseFoodIcon.imageset/chinaFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/fastFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/fastFoodIcon.imageset/fastFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/japaneseFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/japaneseFoodIcon.imageset/japanessFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/koreanFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/koreanFoodIcon.imageset/koreanFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/simpleFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/simpleFoodIcon.imageset/simpleFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/westernFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/westernFoodIcon.imageset/westernFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/worldFoodIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/FoodIcon/worldFoodIcon.imageset/worldFoodIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/copy.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/copy.imageset/copy.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.nonselect.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.nonselect.imageset/favorite.nonselect.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.select.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.select.imageset/favoriteSelect.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favoriteBtn.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favoriteBtn.imageset/favoriteBtn.svg
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/ImageButton.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIViewController+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/FindTownColor.swift
  FindTown/FindTownUI/Sources/FindTownUI/Label/ToastLabel.swift
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Blue.colorset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Green.colorset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Orange.colorset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Pink.colorset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Primary30.colorset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Primary40.colorset/Contents.json
Labels: ♻️ 리팩토링, 💄 UI

#65 시작화면 UI 개선
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Application/AppDelegate.swift
  FindTown/FindTown/Data/DataMapping/Reponse/LoginConfirmReponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/LogoutResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/ReissueResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TokenInformationDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TokenPayloadDTO.swift
  FindTown/FindTown/Data/Repository/Auth/DefaultAppleAuthRepository.swift
  FindTown/FindTown/Data/Repository/Auth/DefaultAuthRepository.swift
  FindTown/FindTown/Data/Repository/Auth/DefaultKakaoAuthRepository.swift
  FindTown/FindTown/Data/Repository/Token/DefaultTokenRepository.swift
  FindTown/FindTown/Data/Repository/Token/TokenManager.swift
  FindTown/FindTown/Data/Requests/Auth/AuthLoginRequest.swift
  FindTown/FindTown/Data/Requests/Auth/ReissueRequest.swift
  FindTown/FindTown/Data/Requests/Member/LoginConfirmRequest.swift
  FindTown/FindTown/Data/Requests/Member/LogoutRequest.swift
  FindTown/FindTown/Data/Requests/Member/SignupRequest.swift
  FindTown/FindTown/Data/Storage/KeyChain/KeyChainManager.swift
  FindTown/FindTown/Domain/UseCase/AuthUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupViewModelDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/Common/Flow/AppCoordinator.swift
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_1024x1024.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_20x20@1x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_20x20@2x 1.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_20x20@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_20x20@3x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_29x29@1x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_29x29@2x 1.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_29x29@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_29x29@3x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_40x40@1x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_40x40@2x 1.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_40x40@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_40x40@3x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_60x60@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_60x60@3x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_76x76@1x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_76x76@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/App_Icon_83.5x83.5@2x.png
  FindTown/FindTown/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/logo.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/logo.imageset/logo.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/symbol.red.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/symbol.red.imageset/symbol_red.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/symbol.white.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/symbol.white.imageset/symbol_white.svg
  FindTown/FindTown/Resource/Base.lproj/LaunchScreen.storyboard
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Error/FTNetworkError.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Network/Session.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIViewController+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/PopUp/NoticeAlertPopUpViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/ToolTip/ToolTip.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#66 홈 화면 UI 개선
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/KakaoAddressViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/FilterSheetType.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/FilterSheetCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/SearchCountyCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/TrafficCollectionView.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SelectCountyViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SelectCountyViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SubViews/ServiceMapPopUpViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowVillageList/ShowVillageListViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/serviceMap.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/serviceMap.imageset/serviceMap.svg
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseWebViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/RatingRadioButton.swift
Labels: ♻️ 리팩토링, ✨ 기능, 💄 UI

#67 홈, 마이페이지 테스트 용 UI 추가 개선
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/townList.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/townList.imageset/townList.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/townList_searched.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/townList_searched.imageset/townList_searched.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/homeLogo.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/logo/homeLogo.imageset/logo_small.svg
Labels: 💄 UI

#69 로그인, 회원가입 기능 개선
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDown.swift
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDownTableView.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIButton+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/PopUp/NoticeAlertPopUpViewController.swift
Labels: 🐞 버그, ♻️ 리팩토링

#68 [찜 & 동네소개] UI 수정
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/townRankToolTip.imageset/townRankToolTip.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Eco.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Eco.imageset/Eco.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Emoji emotions.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Emoji emotions.imageset/Emoji emotions.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Home work.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Home work.imageset/Home work.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Icon_Information.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Icon_Information.imageset/Icon_Information.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Local taxi.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Local taxi.imageset/Local taxi.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Policy-2.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Policy-2.imageset/Policy-2.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Policy.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Policy.imageset/Policy.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Warning.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/Warning.imageset/Warning.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/map_icon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/TownIntro/map_icon.imageset/map_icon.svg
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
  FindTown/FindTownUI/Sources/FindTownUI/ToolTip/ToolTip.swift
Labels: ♻️ 리팩토링, 💄 UI

#70 마이페이지 네트워크 연결
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/MemberInfomationResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Request/MemberIdDTO.swift
  FindTown/FindTown/Data/Repository/Auth/DefaultAuthRepository.swift
  FindTown/FindTown/Data/Repository/Member/MemberRepository.swift
  FindTown/FindTown/Domain/Entities/FilterModel.swift
  FindTown/FindTown/Domain/Entities/ReviewModel.swift
  FindTown/FindTown/Domain/UseCase/MemberUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginViewModelDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewModel.swift
  FindTown/FindTown/Presentation/Common/Flow/AppCoordinator.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/FilterSheetType.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/Infra.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/FilterSheetCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetType.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SelectCountyViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewSection.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/MyTownReviewViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/MyTownReviewViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/SubViews/ReviewTableViewCell.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/SubViews/CollectionHeaderView.swift
Labels: ♻️ 리팩토링, ✨ 기능

#71 동네 지도에 행정동 좌표 나타내는 기능
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/TownMapLocationDTO.swift
  FindTown/FindTown/Data/Repository/Map/DefaultMapRepository.swift
  FindTown/FindTown/Data/Requests/Map/TownLocationRequest.swift
  FindTown/FindTown/Domain/Constant/MapConstant.swift
  FindTown/FindTown/Domain/Entities/City.swift
  FindTown/FindTown/Domain/Entities/ThemaStore.swift
  FindTown/FindTown/Domain/Entities/VillageLocationInformation.swift
  FindTown/FindTown/Domain/Enumerations/CityCode.swift
  FindTown/FindTown/Domain/Enumerations/InfraCategory.swift
  FindTown/FindTown/Domain/Enumerations/ThemaCategory.swift
  FindTown/FindTown/Domain/Protocol/MCategory.swift
  FindTown/FindTown/Domain/UseCase/MapUseCase.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapCategoryCollectionViewCell.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/infra.cafe.icon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/infra.cafe.icon.imageset/cafeIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/thema.notebook.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/thema.notebook.imageset/thema.notebook.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/thema.restaurant.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/thema.restaurant.imageset/thema.restaurant.svg
Labels: ♻️ 리팩토링, ✨ 기능

#73 토큰 재발급 로직 개선
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/Repository/Auth/DefaultAuthRepository.swift
  FindTown/FindTown/Data/Repository/Member/DefaultMemberRepository.swift
  FindTown/FindTown/Data/Repository/Member/MemberRepository.swift
  FindTown/FindTown/Domain/UseCase/AuthUseCase.swift
  FindTown/FindTown/Domain/UseCase/MemberUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewModel.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeader.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeaderField.swift
Labels: 🐞 버그, ♻️ 리팩토링

#76 회원 탈퇴, 로그아웃 로직 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/MemberInfomationResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/MemberResignDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/TokenInformationDTO.swift
  FindTown/FindTown/Data/Repository/Member/DefaultMemberRepository.swift
  FindTown/FindTown/Data/Requests/Member/ResignRequest.swift
  FindTown/FindTown/Domain/UseCase/MemberUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
  FindTown/FindTownCore/Sources/FindTownCore/Coordinator/FlowCoordinator.swift
  FindTown/FindTownCore/Sources/FindTownCore/Coordinator/PresentationStyle.swift
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDown.swift
  FindTown/FindTownUI/Sources/FindTownUI/PopUp/AlertSuccessCancelPopUpViewController.swift
Labels: ♻️ 리팩토링, ✨ 기능

#77 유저정보 불러오는 에러 수정
  FindTown/FindTown/Data/DataMapping/Reponse/MemberInfomationResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Request/MemberSignupDTO.swift
  FindTown/FindTown/Domain/Entities/SingupUserModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
Labels: 🐞 버그, ♻️ 리팩토링

#78 UserDefaultPropertyWrapper 추가 및 isAnonymous 설정
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown.xcodeproj/xcuserdata/jsy.xcuserdatad/xcschemes/xcschememanagement.plist
  FindTown/FindTown/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  FindTown/FindTown/Data/Storage/UserDefaults/UserDefaultsWrapper.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
Labels: ✨ 기능

#81 유저정보 변경, 마이페이지 유저디폴트 세팅
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/LoginConfirmReponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Reponse/MemberInfomationResponseDTO.swift
  FindTown/FindTown/Domain/UseCase/AuthUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginViewModelDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/Common/Flow/AppCoordinator.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/Anonymous/MyPageAnonymousViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/MyTownReviewViewModel.swift
Labels: 🐞 버그, ♻️ 리팩토링

#82 검색 로직 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/TownSearchResponseDTO.swift
  FindTown/FindTown/Data/DataMapping/Request/TownSearchDTO.swift
  FindTown/FindTown/Data/Repository/Town/DefaultTownRepository.swift
  FindTown/FindTown/Data/Requests/Town/TownSearchRequest.swift
  FindTown/FindTown/Domain/UseCase/TownUseCase.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/SearchScene/Flows/SearchCoordinator.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewModel.swift
Labels: ✨ 기능

#84 닉네임 변경 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/ChangeNicknameResponseDTO.swift
  FindTown/FindTown/Data/Repository/Member/DefaultMemberRepository.swift
  FindTown/FindTown/Data/Requests/Member/ChangeNicknameRequest.swift
  FindTown/FindTown/Domain/UseCase/MemberUseCase.swift
  FindTown/FindTown/Presentation/MyPageScene/Flows/MyPageCoordinator.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/ChangeNickname/ChangeNicknameViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyPageViewModel.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HttpMethod.swift
  FindTown/FindTownUI/Sources/FindTownUI/PopUp/NoticeAlertPopUpViewController.swift
Labels: ✨ 기능

#83 동네지도 테마 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/MapThemaStoreResponseDTO.swift
  FindTown/FindTown/Data/Repository/Map/DefaultMapRepository.swift
  FindTown/FindTown/Data/Requests/Map/ThemaStoreRequest.swift
  FindTown/FindTown/Domain/Entities/Category.swift
  FindTown/FindTown/Domain/Entities/ThemaStore.swift
  FindTown/FindTown/Domain/Enumerations/InfraCategory.swift
  FindTown/FindTown/Domain/Enumerations/MapTransition.swift
  FindTown/FindTown/Domain/Enumerations/StoreDetailType.swift
  FindTown/FindTown/Domain/Enumerations/ThemaCategory.swift
  FindTown/FindTown/Domain/Protocol/Category.swift
  FindTown/FindTown/Domain/UseCase/MapUseCase.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapStoreCollectionViewCell.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/StoreCollectionViewFlowLayout.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/chip.chat.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/chip.chat.imageset/chip.chat.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.nonSelect.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.nonSelect.imageset/marker.nonSelect.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.select.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.select.imageset/marker.select.svg
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
Labels: ✨ 기능

#80 동네소개 네트워크 연결
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/TownIntroduceResponseDTO.swift
  FindTown/FindTown/Data/Repository/Town/DefaultTownRepository.swift
  FindTown/FindTown/Data/Requests/Town/TownIntroduceRequest.swift
  FindTown/FindTown/Domain/Entities/TownIntroduce.swift
  FindTown/FindTown/Domain/Entities/TownRank.swift
  FindTown/FindTown/Domain/Enumerations/Traffic.swift
  FindTown/FindTown/Domain/UseCase/TownUseCase.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetType.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/HotPlaceCollectionView/HotPlaceCollectionView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/HotPlaceCollectionView/HotPlaceCollectionViewCell.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/HotPlaceCollectionView/HotPlaceCollectionViewLayout.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/TownMoodCollectionView/TownMoodCollectionView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/TownMoodCollectionView/TownMoodCollectionViewCell.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/TownMoodCollectionView/TownMoodCollectionViewLayout.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/TownRank/TownRankView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/SubViews/TrafficTip/TrafficTipView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/TownIntroduceViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/TownIntroduceViewModel.swift
Labels: ✨ 기능

#89 동네지도 인프라 지도 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/MapThemaStoreResponseDTO.swift
  FindTown/FindTown/Data/Repository/Map/DefaultMapRepository.swift
  FindTown/FindTown/Domain/Entities/City.swift
  FindTown/FindTown/Domain/Entities/DetailCategory.swift
  FindTown/FindTown/Domain/Entities/InfraStore.swift
  FindTown/FindTown/Domain/Entities/MapData.swift
  FindTown/FindTown/Domain/Entities/Store.swift
  FindTown/FindTown/Domain/Entities/Thema.swift
  FindTown/FindTown/Domain/Enumerations/InfraCategory.swift
  FindTown/FindTown/Domain/Enumerations/InfraSubCategory.swift
  FindTown/FindTown/Domain/Enumerations/StoreType.swift
  FindTown/FindTown/Domain/Enumerations/TownMood.swift
  FindTown/FindTown/Domain/Enumerations/TownRank.swift
  FindTown/FindTown/Domain/UseCase/MapUseCase.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapDetailCategoryView.swift
  FindTown/FindTown/Presentation/SearchScene/Flows/SearchCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/TownIntroduceViewController.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/maker.police.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/maker.police.imageset/maker.police.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.cafe.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.cafe.imageset/marker.cafe.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.cctv.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.cctv.imageset/marker.cctv.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.convenience.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.convenience.imageset/marker.convenience.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.daiso.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.daiso.imageset/marker.daiso.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.fitnessCenter.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.fitnessCenter.imageset/marker.fitnessCenter.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.groceryStore.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.groceryStore.imageset/marker.groceryStore.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.hospital.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.hospital.imageset/marker.hospital.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.largeHospital.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.largeHospital.imageset/marker.large.hospital.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.park.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.park.imageset/marker.park.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.pharmacy.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.pharmacy.imageset/marker.pharmacy.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.pilates.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.pilates.imageset/marker.pilates.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.safetyBell.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.safetyBell.imageset/marker.safetyBell.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.sportsCenter.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.sportsCenter.imageset/marker.sportsCenter.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.superMarket.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/marker/marker.superMarket.imageset/marker.superMarket.svg
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIViewController+Extension.swift
Labels: ♻️ 리팩토링, ✨ 기능

#90 동네 지도 내 찜 기능 추가
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Domain/Enumerations/InformationPresentType.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
Labels: ♻️ 리팩토링, ✨ 기능

#92 QA 반영 및 오류 개선
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Data/DataMapping/Reponse/LoginResponseDTO.swift
  FindTown/FindTown/Data/Repository/Auth/DefaultAuthRepository.swift
  FindTown/FindTown/Data/Repository/Token/DefaultTokenRepository.swift
  FindTown/FindTown/Data/Requests/Auth/AuthLoginRequest.swift
  FindTown/FindTown/Domain/Entities/TokenData.swift
  FindTown/FindTown/Domain/Enumerations/InformationPresentType.swift
  FindTown/FindTown/Domain/UseCase/AuthUseCase.swift
  FindTown/FindTown/Domain/UseCase/MemberUseCase.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewController.swift
  FindTown/FindTown/Presentation/Common/Flow/AppCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/MapScene/Flows/MapCoordinator.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewModel.swift
  FindTown/FindTown/Presentation/MapScene/Map/SubViews/MapStoreCollectionViewCell.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/bellIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/bellIcon.imageset/bellIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/healthIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/healthIcon.imageset/healthIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/hospitalIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/hospitalIcon.imageset/hospitalIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/infra.cafe.icon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/infra.cafe.icon.imageset/cafeIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/martIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/martIcon.imageset/martIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/pharmacyIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/pharmacyIcon.imageset/pharmacyIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/storeIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/storeIcon.imageset/storeIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/walkIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/InfraCategory/walkIcon.imageset/walkIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.select.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.select.imageset/favorite.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/favorite.select.imageset/favoriteSelect.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/themaCategory/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/themaCategory/thema.notebook.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/themaCategory/thema.notebook.imageset/thema.notebook.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/themaCategory/thema.restaurant.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/MapVC/themaCategory/thema.restaurant.imageset/thema.restaurant.svg
  FindTown/FindTown/Resource/Base.lproj/LaunchScreen.storyboard
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseBottomSheetViewController.swift
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/CheckBox.swift
  FindTown/FindTownUI/Sources/FindTownUI/ToolTip/ToolTip.swift
Labels: ♻️ 리팩토링

#93 디자인 QA 반영
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/MyTownReviewViewController.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/nature.imageset/nature.svg
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIViewController+Extension.swift
Labels: ♻️ 리팩토링

#95 QA 반영 및 오류 개선
  FindTown/FindTown/Domain/Entities/TownTableModel.swift
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/MyTownReviewViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/MyPage/MyTownReview/SubViews/ReviewTableView.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewController.swift
  FindTown/FindTown/Presentation/SearchScene/Search/ShowVillageList/ShowVillageListViewModel.swift
  FindTown/FindTown/Presentation/SearchScene/Search/SubViews/ServiceMapPopUpViewController.swift
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
Labels: 🐞 버그, ♻️ 리팩토링

#96 Map 사용성 개선 및 QA 수정사항 반영
  FindTown/FindTown/Domain/Enumerations/InfraSubCategory.swift
  FindTown/FindTown/Presentation/MapScene/Map/MapViewController.swift
  FindTown/FindTown/Presentation/MyPageScene/Anonymous/MyPageAnonymousViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/TownIntroduceViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntroduce/TownIntroduceViewModel.swift
  FindTown/FindTown/Resource/Base.lproj/LaunchScreen.storyboard
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseBottomSheetViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/ToolTip/ToolTip.swift
Labels: ♻️ 리팩토링
