Repository FindTown/FindTown-iOS, pull requests merged in 2023-01, with the labels that each got.

#32 NaverMap SPM 추가
  .gitignore
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindTown/FindTown/Application/AppDelegate.swift
  FindTown/FindTown/Resource/Info.plist
  FindTown/FindTownCore/Sources/FindTownCore/Extensions/Bundle+Extension.swift
Labels: ⚙️ 설정

#31 UI Component 중 DropDown 구현
  FindTown/FindTownCore/Sources/FindTownCore/Extensions/UIViewController+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDown.swift
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDownCell.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/CALayer+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/PopUp/AlertPopUpViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/checkmark.imageset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/checkmark.imageset/checkmark.svg
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/dropButtonBlack.imageset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/dropButtonBlack.imageset/dropButtonBlack.svg
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/dropButtonGrey.imageset/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Resource/Assets.xcassets/Image/dropButtonGrey.imageset/dropButtonGrey.svg
Labels: ✨ 기능

#33 Login, SignUpNickName Scene 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinatorDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinatorDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/KakaoAddressViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/YearMonthPickerView.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/SignUpNickNameViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/LoginVC/AppleIcon.imageset/AppleIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/LoginVC/AppleIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/LoginVC/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/LoginVC/KakaoIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/LoginVC/KakaoIcon.imageset/kakaoIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/SignupVC/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/SignupVC/MapPinIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/SignupVC/MapPinIcon.imageset/MapPinIcon.svg
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
  FindTown/FindTownCore/Sources/FindTownCore/Extensions/String+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButton.swift
  FindTown/FindTownUI/Sources/FindTownUI/Button/FTButton/FTButtonStyle.swift
Labels: ✨ 기능, 💄 UI

#45 카카오 로그인
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindTown/FindTown/Application/AppDelegate.swift
  FindTown/FindTown/Application/SceneDelegate.swift
  FindTown/FindTown/Domain/Manager/KeyChain/KeyChainAccount.swift
  FindTown/FindTown/Domain/Manager/KeyChain/KeyChainError.swift
  FindTown/FindTown/Domain/Manager/KeyChain/KeyChainManager.swift
  FindTown/FindTown/Domain/Manager/TokenManager.swift
  FindTown/FindTown/Manager/AppleSigninManager.swift
  FindTown/FindTown/Manager/KakaoSigninManager.swift
  FindTown/FindTown/Manager/SigninManagerProtocol.swift
  FindTown/FindTown/Presentation/AuthScene/Entities/SignupUserModel.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/LoginCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupViewModelDelegate.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Login/LoginViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/AgreePolicy/AgreePolicyViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/LocationAndYears/LocationAndYearsViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewModel.swift
  FindTown/FindTown/Presentation/Common/Flow/AppCoordinator.swift
  FindTown/FindTown/Presentation/Utils/UserDefaultUtil.swift
  FindTown/FindTown/Resource/Info.plist
  FindTown/FindTownCore/Sources/FindTownCore/Extensions/Bundle+Extension.swift
Labels: ✨ 기능

#48 찜 탭 화면 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/Common/Flow/TabBarCoordinator.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/Favorite1ViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/Favorite1ViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/AnonymousView.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/EmptyView.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/FavoriteTableView.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/TempTableViewCell.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/anonymousIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/anonymousIcon.imageset/anonymousIcon.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/emptyIcon.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/emptyIcon.imageset/emptyIcon.svg
  FindTown/FindTown/Resource/Base.lproj/LaunchScreen.storyboard
  FindTown/FindTownUI/Sources/FindTownUI/DropDown/DropDown.swift
Labels: ✨ 기능

#49 홈 메인 + 필터 화면 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown.xcodeproj/project.xcworkspace/xcuserdata/sunghun.xcuserdatad/UserInterfaceState.xcuserstate
  FindTown/FindTown.xcodeproj/xcuserdata/sunghun.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  FindTown/FindTown/Presentation/AuthScene/Flows/SignupCoordinator.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewModel.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/Infra.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/Traffic.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/FilterSheetCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/InfraIconStackView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/TrafficCollectionView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/TrafficCollectionViewCell.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/SubViews/TrafficCollectionViewFlowLayout.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewCell.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/FilterCollectionViewFlowLayout.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableView.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/arrowDown.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/arrowDown.imageset/arrow_down.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/arrowDown_selected.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/arrowDown_selected.imageset/arrowDown_selected.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/favorite.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/favorite.imageset/favorite.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/favorite_selected.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/favorite_selected.imageset/favorite_selected.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/filter.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/filter.imageset/filter.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/health.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/health.imageset/health.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/hospital.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/hospital.imageset/hospital.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/nature.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/nature.imageset/nature.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/reset.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/reset.imageset/reset.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/search.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/search.imageset/search.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/shop.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/shop.imageset/shop.svg
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseBottomSheetViewController.swift
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/CALayer+Extension.swift
  FindTown/FindTownUI/Sources/FindTownUI/Tabman/TabmanMenuBar.swift
  FindTown/FindTownUI/Sources/FindTownUI/Tabman/TabmanMenuBarCell.swift
Labels: ✨ 기능, 💄 UI

#51 API NetworkManager 구현
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Common/AnyEncodable.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Common/TaskType.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Common/URLSessionProtocol.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Error/FTNetworkError.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Extensions/Data+Extension.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Extensions/URL+Extension.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Extensions/URLRequest+Extension.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/FindTownNetwork.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeader.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeaderField.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HTTPHeaders.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Http/HttpMethod.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Network/Network.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Network/Session.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Request/BaseRequest.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Request/Request.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Response/BaseResponse.swift
  FindTown/FindTownNetwork/Sources/FindTownNetwork/Response/Response.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/FindTownNetworkTests.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/NetworkTests.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/SessionTests.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/TestDoubles/MockData.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/TestDoubles/MockRequest.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/TestDoubles/MockResponse.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/TestDoubles/MockSession.swift
  FindTown/FindTownNetwork/Tests/FindTownNetworkTests/TestDoubles/MockURLSession.swift
Labels: ✨ 기능, 테스트

#52 찜 탭 townTableViewCell 적용
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/Favorite1ViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/FavoriteTableView.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/SubViews/TempTableViewCell.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
Labels: ✨ 기능, 💄 UI

#53 홈 검색 UI 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Presentation/HomeScene/Flows/HomeCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Flows/SearchCountyCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/HomeViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SelectCountyViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/SelectCounty/SelectCountyViewModel.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowDongList/ShowDongListViewController.swift
  FindTown/FindTown/Presentation/HomeScene/SearchCounty/ShowDongList/ShowDongListViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/ei_close.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/HomeVC/ei_close.imageset/ei_close.svg
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/UIViewController+Extension.swift
Labels: ✨ 기능, 💄 UI

#54 Core에서 UI asset파일이 불러오지 않는 문제 해결
  FindTown/FindTownCore/Package.swift
  FindTown/FindTownCore/Sources/FindTownCore/Base/BaseNavigationController.swift
  FindTown/FindTownCore/Sources/FindTownCore/Resource/Assets.xcassets/Contents.json
  FindTown/FindTownCore/Sources/FindTownCore/Resource/Assets.xcassets/Image/Back.imageset/Back.svg
  FindTown/FindTownCore/Sources/FindTownCore/Resource/Assets.xcassets/Image/Back.imageset/Contents.json
  FindTown/FindTownCore/Sources/FindTownCore/Resource/Assets.xcassets/Image/Contents.json
  FindTown/FindTownUI/Sources/FindTownUI/Extensions/Bundle+Extension.swift
Labels: 🐞 버그

#57 동네소개 UI 구현
  FindTown/FindTown.xcodeproj/project.pbxproj
  FindTown/FindTown/Domain/Entities/TownMood.swift
  FindTown/FindTown/Domain/Entities/TownRank.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/FavoriteTown/FavoriteTownViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/Nickname/NicknameViewController.swift
  FindTown/FindTown/Presentation/AuthScene/Signup/TownMood/TownMoodViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewController.swift
  FindTown/FindTown/Presentation/FavoriteScene/Favorite/FavoriteViewModel.swift
  FindTown/FindTown/Presentation/FavoriteScene/Flows/FavoriteCoordinator.swift
  FindTown/FindTown/Presentation/HomeScene/DemoHomeEntitie/Traffic.swift
  FindTown/FindTown/Presentation/HomeScene/Home/Sheets/FilterBottomSheetViewController.swift
  FindTown/FindTown/Presentation/HomeScene/Home/SubViews/TownTableViewCell.swift
  FindTown/FindTown/Presentation/TownIntroScene/Flows/TownIntroCoordinator.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/HotPlaceCollectionView/HotPlaceCollectionView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/HotPlaceCollectionView/HotPlaceCollectionViewCell.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/HotPlaceCollectionView/HotPlaceCollectionViewLayout.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TownMoodCollectionView/TownMoodCollectionView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TownMoodCollectionView/TownMoodCollectionViewCell.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TownMoodCollectionView/TownMoodCollectionViewLayout.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TownRank/TownRankView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/SubViews/TrafficTip/TrafficTipView.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewController.swift
  FindTown/FindTown/Presentation/TownIntroScene/TownIntro/TownIntroViewModel.swift
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Eco.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Eco.imageset/Eco.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Emoji emotions.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Emoji emotions.imageset/Emoji emotions.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Home work.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Home work.imageset/Home work.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Icon_Information.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Icon_Information.imageset/Icon_Information.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Local taxi.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Local taxi.imageset/Local taxi.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Policy-2.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Policy-2.imageset/Policy-2.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Policy.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Policy.imageset/Policy.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Warning.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/Warning.imageset/Warning.svg
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/townRankToolTip.imageset/Contents.json
  FindTown/FindTown/Resource/Assets.xcassets/Image/FavoriteVC/townRankToolTip.imageset/townRankToolTip.svg
Labels: ✨ 기능
